modLoader="javafml"
loaderVersion="[47,)"

license="LGPL-2.1-or-later"
issueTrackerURL=""
showAsResourcePack=false

[[mods]]
modId="better_spellcasting"
version="${version}"
displayName="Better Spellcasting"
displayURL=""
logoFile=""
credits=""
authors="Kayn"
description='''
  A mod that integrates Better Combat with Iron's Spellbooks by allowing you to assign spells to weapon attacks.
  '''
displayTest="MATCH_VERSION"

[[dependencies.better_spellcasting]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.better_spellcasting]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.better_spellcasting]]
modId="irons_spellbooks"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.better_spellcasting]]
modId="better_combat"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"